import { ClaimTicket } from '@/types/claim'

export const MOCK_TICKETS: ClaimTicket[] = [
  {
    id: '1',
    claimRef: 'INCA-2025-0347',
    callerName: 'Alexandra Müller',
    callerPhone: '+49 30 1234 5678',
    date: 'Apr 25, 2025',
    duration: '04:23',
    lossType: 'Rear-end collision',
    location: 'A100, Berlin',
    fields: [
      { key: 'Date',            value: '2025-04-25 ~10:00' },
      { key: 'Location',        value: 'A100, Tempelhof, Berlin' },
      { key: 'Loss type',       value: 'Rear-end collision' },
      { key: '3rd party plate', value: 'B-RT 4821' },
      { key: 'Police report',   value: 'BP-2025-04-25-0347' },
      { key: 'Injuries',        value: 'None reported' },
      { key: 'Drivable',        value: 'Unknown' },
      { key: 'Policy no.',      value: null },
      { key: 'Driver scope',    value: null },
      { key: 'Repair shop',     value: null },
    ],
    messages: [
      { id: '1', role: 'agent',  text: 'Thank you for calling INCA claims. This is Sarah. Are you safe? Is everyone okay?', timestamp: '00:00:08' },
      { id: '2', role: 'caller', text: 'Yes I am fine. My car was hit from behind on the A100.', timestamp: '00:00:22' },
      { id: '3', role: 'agent',  text: 'I am glad you are okay. Can you tell me when this happened?', timestamp: '00:00:35' },
      { id: '4', role: 'caller', text: 'Today around 10 AM near the Tempelhof junction.', timestamp: '00:00:58' },
      { id: '5', role: 'agent',  text: 'And the other vehicle — did they stop at the scene?', timestamp: '00:01:15' },
      { id: '6', role: 'caller', text: 'Yes they stopped. I have their plate: B-RT 4821.', timestamp: '00:01:40' },
    ],
  },
  {
    id: '2',
    claimRef: 'INCA-2025-0348',
    callerName: 'Mohamed Hassan',
    callerPhone: '+49 170 5551234',
    date: 'Apr 25, 2025',
    duration: '05:11',
    lossType: 'Parking damage',
    location: 'Mitte, Berlin',
    fields: [
      { key: 'Date',            value: '2025-04-25 ~14:30' },
      { key: 'Location',        value: 'Unter den Linden, Mitte' },
      { key: 'Loss type',       value: 'Parking damage' },
      { key: '3rd party plate', value: null },
      { key: 'Police report',   value: null },
      { key: 'Injuries',        value: 'None' },
      { key: 'Drivable',        value: 'Yes' },
      { key: 'Policy no.',      value: 'POL-9988-DE' },
      { key: 'Driver scope',    value: 'Policyholder' },
      { key: 'Repair shop',     value: 'Auto Center Mitte' },
    ],
    messages: [
      { id: '1', role: 'agent',  text: 'Thank you for calling INCA claims. This is Sarah. Are you safe?', timestamp: '00:00:05' },
      { id: '2', role: 'caller', text: 'Yes I am fine. Someone hit my parked car and drove away.', timestamp: '00:00:18' },
      { id: '3', role: 'agent',  text: 'I am sorry to hear that. When did this happen?', timestamp: '00:00:30' },
      { id: '4', role: 'caller', text: 'Around 2:30 PM today on Unter den Linden.', timestamp: '00:00:50' },
    ],
  },
  {
    id: '3',
    claimRef: 'INCA-2025-0349',
    callerName: 'Jonas Weber',
    callerPhone: '+49 152 9876543',
    date: 'Apr 25, 2025',
    duration: '03:47',
    lossType: 'Wildlife collision',
    location: 'B96, Brandenburg',
    fields: [
      { key: 'Date',            value: '2025-04-25 ~06:15' },
      { key: 'Location',        value: 'B96, Brandenburg' },
      { key: 'Loss type',       value: 'Wildlife collision' },
      { key: '3rd party plate', value: null },
      { key: 'Police report',   value: 'BP-2025-04-25-0112' },
      { key: 'Injuries',        value: 'Minor — checked by paramedics' },
      { key: 'Drivable',        value: 'No — towed' },
      { key: 'Policy no.',      value: 'POL-4421-DE' },
      { key: 'Driver scope',    value: 'Policyholder' },
      { key: 'Repair shop',     value: null },
    ],
    messages: [
      { id: '1', role: 'agent',  text: 'Thank you for calling INCA claims. This is Sarah. Are you safe?', timestamp: '00:00:06' },
      { id: '2', role: 'caller', text: 'I think so. I hit a deer on the B96 this morning. The front is badly damaged.', timestamp: '00:00:25' },
      { id: '3', role: 'agent',  text: 'That sounds frightening. Was the police called?', timestamp: '00:00:40' },
      { id: '4', role: 'caller', text: 'Yes I have the case number: BP-2025-04-25-0112.', timestamp: '00:01:05' },
    ],
  },
]
